# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0002_secciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secciones',
            new_name='Seccion',
        ),
    ]
