# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0003_auto_20171012_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='nombre',
        ),
    ]
