# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import festivalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0007_auto_20171013_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='fechinscrip',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha l\xedmite de inscripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='anio',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2017, verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='logo',
            field=models.ImageField(upload_to=festivalapp.models.get_logo_path, verbose_name='Logo'),
        ),
    ]
