# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0008_auto_20171013_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='descripcion1',
            field=models.TextField(default='', max_length=500, verbose_name='T\xedtulo 1'),
        ),
        migrations.AddField(
            model_name='festival',
            name='descripcion2',
            field=models.TextField(default='', max_length=500, verbose_name='T\xedtulo 2'),
        ),
    ]
