# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0009_auto_20171013_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='fechinicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha inicio de inscripci\xf3n'),
        ),
        migrations.AddField(
            model_name='festival',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='descripcion1',
            field=models.TextField(default='', max_length=500, verbose_name='Descripci\xf3n'),
        ),
    ]
