# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0010_auto_20171013_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='secciones',
            field=models.ManyToManyField(to='festivalapp.Seccion'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='descripcion1',
            field=models.TextField(default='', max_length=500, verbose_name='Descripci\xf3n 1'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='descripcion2',
            field=models.TextField(default='', max_length=500, verbose_name='Descripci\xf3n 2'),
        ),
    ]
