# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0011_auto_20171013_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='fechinicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio de inscripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fechinscrip',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha l\xedmite de inscripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='secciones',
            field=models.ManyToManyField(blank=True, to='festivalapp.Seccion'),
        ),
    ]
