# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0012_auto_20171013_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='descripcion1',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='descripcion2',
        ),
        migrations.AddField(
            model_name='festival',
            name='descripcion',
            field=models.TextField(default='', max_length=500, verbose_name='Descripci\xf3n'),
        ),
    ]
