# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0013_auto_20171013_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='participante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='premaiada',
            field=models.BooleanField(default=False),
        ),
    ]
