# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0014_auto_20171015_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='premaiada',
            new_name='premiada',
        ),
    ]
