# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0015_auto_20171015_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='festival',
            field=models.IntegerField(default=2017),
        ),
    ]
